# Generated by Django 5.1.1 on 2024-10-10 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_follow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.AddField(
            model_name="follow",
            name="following",
            field=models.ManyToManyField(
                related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
