# Generated by Django 5.1.1 on 2024-10-11 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_remove_follow_following_follow_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="likes",
        ),
        migrations.AddField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
