# Generated by Django 5.1.1 on 2024-09-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watchlist_bid_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlist",
        ),
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlisted_by", to="auctions.listing"
            ),
        ),
    ]
