# Generated by Django 5.1.1 on 2024-09-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_remove_listing_watchlist_listing_is_active_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bid",
        ),
    ]
