# Generated by Django 5.1.1 on 2024-09-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electronics", "Electronics"),
                    ("Furniture", "Furniture"),
                    ("Clothing", "Clothing"),
                    ("Fashion", "Fashion"),
                    ("Other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
